// This file is automatically generated by safe-router.
// Do not modify this file manually.
import { buildRoute } from 'safe-router/helpers'

export const routes = {
  /**
   * @returns /
   */
  get: buildRoute('/'),
  about: {
    /**
     * @returns /about
     */
    get: buildRoute('/about'),
  },
  api: {
    /**
     * @returns /api
     */
    get: buildRoute('/api'),
    apiRoute: (...api_apiRoute: string[]) => ({
      /**
       * @returns /api/{apiRoute[0]}/{apiRoute[1]}/...
       */
      get: buildRoute(`/api/${api_apiRoute.join('/')}`),
    }),
  },
  hello: {
    params: (...hello_params: string[]) => ({
      /**
       * @returns /hello/{params[0]}/{params[1]}/...
       */
      get: buildRoute(`/hello/${hello_params.join('/')}`),
    }),
  },
  products: {
    /**
     * @returns /products
     */
    get: buildRoute('/products'),
    id: (products_id: string) => ({
      /**
       * @returns /products/{id}
       */
      get: buildRoute(`/products/${products_id}`),
      details: {
        /**
         * @returns /products/{id}/details
         */
        get: buildRoute<{ tab: string }>(`/products/${products_id}/details`),
      },
    }),
  },
}

export type RouteParams = {
  '.': {}
  'about': {}
  'api': {}
  'api.apiRoute': { apiRoute: string[] }
  'hello.params': { params: string[] }
  'products': {}
  'products.id': { id: string }
  'products.id.details': { id: string }
}
