import { buildTree } from './buildTree'
import { compileTree } from './compileTree'

export function compile(appDir: string) {
	const tree = buildTree(appDir)
	const compiledTree = compileTree(tree)

	const fileContent = `// This file is automatically generated by safe-router.
// Do not modify this file manually.

export const routes = ${compiledTree}`

	return fileContent
}
