import { buildTree } from './buildTree'
import { compileParams } from './compileParams'
import { compileRoutes } from './compileRoutes'

export function compile(appDir: string) {
	const tree = buildTree(appDir)
	const compiledRoutes = compileRoutes(tree)
	const compiledParams = compileParams(tree)

	const fileContent = `// This file is automatically generated by safe-router.
// Do not modify this file manually.

export const routes = ${compiledRoutes}

export type RouteParams = ${compiledParams}`

	return fileContent
}
