import { buildTree } from './buildTree'
import { compileTree } from './compileTree'
import * as fs from 'node:fs'

export function generate(appDir: string, routesFilePath: string) {
	const tree = buildTree(appDir)
	const compiledTree = compileTree(tree)

	const fileContent = `// This file is automatically generated by safe-router.
// Do not modify this file manually.

export const routes = ${compiledTree}`

	fs.writeFileSync(routesFilePath, fileContent, 'utf8')
}
